// <auto-generated />
using System;
using BundestagMine.SqlDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BundestagMine.SqlDatabase.Migrations.BundestagMineTokenDb
{
    [DbContext(typeof(BundestagMineTokenDbContext))]
    [Migration("20230104085831_AddedNewTokenDb")]
    partial class AddedNewTokenDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BundestagMine.Models.Database.MongoDB.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Animacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aspect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Begin")
                        .HasColumnType("int");

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Definiteness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("End")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LemmaValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Morph")
                        .HasColumnType("bit");

                    b.Property<Guid>("NLPSpeechId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Negative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Possessive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PronType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reflex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transitivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerbForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
